# Generated by Django 4.2.30 on 2026-04-15 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter course name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter course description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter lesson title', max_length=200)),
                ('content', models.TextField(help_text='Enter lesson content')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of lesson in course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='Select the course this lesson belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='onlinecourse.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='Enter the question text', max_length=500)),
                ('grade_point', models.PositiveIntegerField(default=1, help_text='Points awarded for correct answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='Select the course this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='onlinecourse.course')),
                ('lesson', models.ForeignKey(help_text='Select the lesson this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='onlinecourse.lesson')),
            ],
            options={
                'ordering': ['lesson', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, help_text='Score achieved', max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Total possible score', max_digits=5)),
                ('is_pass', models.BooleanField(default=False, help_text='Whether the submission is passing')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Submission timestamp')),
                ('course', models.ForeignKey(help_text='Select the course for this submission', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='onlinecourse.course')),
                ('lesson', models.ForeignKey(help_text='Select the lesson for this submission', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='onlinecourse.lesson')),
                ('student', models.ForeignKey(help_text='Select the student who submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(help_text='Enter the choice text', max_length=300)),
                ('is_correct', models.BooleanField(default=False, help_text='Check if this is the correct answer')),
                ('question', models.ForeignKey(help_text='Select the question this choice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='onlinecourse.question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SelectedChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(help_text='Select the choice that was selected', on_delete=django.db.models.deletion.CASCADE, related_name='selected_choices', to='onlinecourse.choice')),
                ('question', models.ForeignKey(help_text='Select the question this choice answers', on_delete=django.db.models.deletion.CASCADE, related_name='selected_choices', to='onlinecourse.question')),
                ('submission', models.ForeignKey(help_text='Select the submission this choice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='selected_choices', to='onlinecourse.submission')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
