# Generated by Django 4.2.30 on 2026-04-15 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Student biography')),
                ('interests', models.CharField(blank=True, help_text='Areas of interest', max_length=200)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='Link to user account', on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learner',
                'verbose_name_plural': 'Learners',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Instructor biography')),
                ('expertise', models.CharField(blank=True, help_text='Area of expertise', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='Link to user account', on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
                'ordering': ['user__username'],
            },
        ),
    ]
